export const userTypes = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_CLEAR: 'REGISTER_CLEAR',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT: 'LOGOUT'
}

export const pizzaTypes = {
  PIZZA_GET_PRODUCTS_SUCCESS: 'PIZZA_GET_PRODUCTS_SUCCESS',
  PIZZA_GET_PRODUCTS_FAILURE: 'PIZZA_GET_PRODUCTS_FAILURE',
  PIZZA_CREATE_PRICE_FROM_SIZE: 'PIZZA_CREATE_PRICE_FROM_SIZE',

  PIZZA_ADD_INGREDIENT: 'PIZZA_ADD_INGREDIENT',
  PIZZA_ADD_UPDATE_INGREDIENT: 'PIZZA_ADD_UPDATE_INGREDIENT',
  PIZZA_REFRESH_INGREDIENTS: 'PIZZA_REFRESH_INGREDIENTS',
  PIZZA_REDUCE_INGREDIENT: 'PIZZA_REDUCE_INGREDIENT',

  PIZZA_CLEAR: 'PIZZA_CLEAR'
}
