export const userConstants = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    REGISTER_COMPLETED: "REGISTER_COMPLETED",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT: "LOGOUT",
}

export const pizzaConstants = {
    PIZZA_CREATE: "PIZZA_CREATE",
    
    PIZZA_CREATE_PRICE: "PIZZA_CREATE_PRICE",
    PIZZA_ADD_INGREDIENT: "PIZZA_ADD_INGREDIENT",
    PIZZA_REDUCE_INGREDIENT: "PIZZA_REDUCE_INGREDIENT",
    PIZZA_UPDATE_INGREDIENTS: "PIZZA_UPDATE_INGREDIENTS"
}

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};
